### ISSUE TITLE
Incorrect instructions for enabling vulnerability alerts

### ISSUE THREAD

**Issue by MikeMcC399** [githubtraining/security-strategy-essentials#17]
**Describe the bug**
This is a follow-on from community discussion [Lab security-strategy-essentials can this only be done through enterprise?](https://github.community/t/lab-security-strategy-essentials-can-this-only-be-done-through-enterprise/143194)

Course instructions do not correspond to current UI:
- "Data services" seems to have been moved and instead refers to "Security & analysis settings".
- There are no check boxes displayed.

**To Reproduce**

1. Go to https://lab.github.com/githubtraining/securing-your-workflows (Latest release February 26, 2020)
2. Click on "Start free course"
Note that Public (Default) is selected. Private is greyed out.    
Click "Begin Securing your workflows".
Course is prepared.
3. Click Start in Course Step 1
"Welcome to Securing your workflows!" is displayed.
The section about enabling data services is not displayed.
4. Using the instructions from the [Quick Reference Guide](https://lab.github.com/public/securing-your-workflows.pdf)
```
1.1. Click the Settings tab in your repository.
1.2. Scroll down until you see Data services.
1.3. Under Data services, click the check boxes to enable all the data services
```
![Data services](https://user-images.githubusercontent.com/66998419/99557404-f114d280-29c2-11eb-8323-7c0535a14777.jpg)

---

![Configure security and analysis features](https://user-images.githubusercontent.com/66998419/99558325-e60e7200-29c3-11eb-8453-fe499118923c.jpg)

7. In "Configure security and analysis features" click on Enable in the section Dependabot alerts.
Only Dependabot alerts should be enabled.
If Dependabot security updates are enabled then the lack of a package-lock.json will cause automatic security updates to fail. In any case, using security updates is not part of the course.

**Expected behavior**
1. Include instructions to enable Dependabot alerts in the online instructions even when the repository is public.
2. Instructions to enable Dependabot alerts should say:
Click on Security in the repository
Click on the Enable button corresponding to Dependabot alerts

**Additional context**
When the [Community article: Lab security-strategy-essentials can this only be done through enterprise?](https://github.community/t/lab-security-strategy-essentials-can-this-only-be-done-through-enterprise/143194) was started there may have been an issue with the proper functioning of Dependabot alerts a couple of days ago, independently of course content. It is however working today (Nov 18, 2020) and nothing in the course has been changed as far as I know.

Note that I am a beginner (which is why I was following the [First Week on GitHub](https://lab.github.com/githubtraining/first-week-on-github) stream). Please excuse any wrong assumptions due to my lack of experience!

**Comment by hectorsector** [comment]
Thanks for the report, @MikeMcC399! Working on a fix now.

**Comment by MikeMcC399** [comment]
@hectorsector 
Thanks for making changes. It doesn't work quite right though for me.

In Step 2, enabling the Dependabot alerts takes me out of the Security tab / Dependabot alerts. (They were not enabled by default for me.) So in order to see the `debug `alert I have to select Security / Dependabit alerts a second time.

**Comment by MikeMcC399** [comment]
Since this issue is closed and the current state was a little unclear, I have opened a new issue #20 to cover the problem remaining.
