### ISSUE TITLE
Poor instructions to enable Dependabot alerts

### ISSUE THREAD

**Issue by MikeMcC399** [githubtraining/security-strategy-essentials#20]
This is a follow-on from the closed issue https://github.com/githubtraining/security-strategy-essentials/issues/17

**Describe the bug**
If the instructions "On the left hand navigation bar, click Dependabot alerts." are followed Dependabots can be enabled, but the following instructions leave the learner stranded.

**To Reproduce**

1. Start course "Security strategy essentials" from https://lab.github.com/githubtraining/security-strategy-essentials
2. Complete Step 1 (Enable GitHub Pages)
3. In Step 2 "Find this repository's vulnerable dependencies"

- Click the Security tab in your repository.
- On the left hand navigation bar, click Dependabot alerts.
- Follow the instructions to enable Dependabot alerts, if they're not already enabled.
- Click on the debug alert.
- Take note of the suggested version.
- Comment in this issue with the suggested update version.

**Expected behavior**
Following the instructions should lead to the vulnerability being shown.

**Suggested changes**
Instead of:
"Click the Security tab in your repository.
On the left hand navigation bar, click Dependabot alerts.
Follow the instructions to enable Dependabot alerts, if they're not already enabled."

write:
"Click the Settings tab in your repository, then click Security & analysis.
If the button "Enable" is shown opposite "Dependabot alerts", then click the button to Enable Dependabot alerts."

now:
Click the Security tab in your repository.
Click "View Dependabot alerts".

which then correctly leads into:
"Click on the debug alert."

**Screenshots**
Here are the screenshots from following the current set of instructions:
- Click the Security tab in your repository.

![Security](https://user-images.githubusercontent.com/66998419/101342339-b5af4a80-3882-11eb-875c-8087f4525438.jpg)

---
- On the left hand navigation bar, click Dependabot alerts.

![image](https://user-images.githubusercontent.com/66998419/101342795-5867c900-3883-11eb-949d-432241a93f4e.png)

---
- Follow the instructions to enable Dependabot alerts, if they're not already enabled.

![image](https://user-images.githubusercontent.com/66998419/101342946-8e0cb200-3883-11eb-9c38-f93f4723547f.png)

---
- Click on the debug alert.

There is no debug alert shown. The step of going to the Security tab and selecting "Dependabot alerts" on the left or "View Dependabot alerts" on the right is missing.

**Comment by MikeMcC399** [comment]
One other thought:

Although Security > Overview allows enabling Dependabot alerts it does not allow disabling them, so this option is not a good way to learn how to enable / disable Dependabots.

Settings > Security & analysis on the other hand allows both enabling and disabling Dependabot alerts, so it should be considered the preferred way of managing the status of Dependabot alerts.

**Comment by a-a-ron** [comment]
Thank you, @MikeMcC399 for this insight to improve the instructions. I've added this to our list of updates/improvements.

**Comment by MikeMcC399** [comment]
I checked [Release v27.0.0](https://github.com/githubtraining/security-strategy-essentials/releases/tag/v27.0.0) and this issue is not yet resolved.

**Comment by chadfawcett** [comment]
FYI: As of today, I'm still met with the outdated instructions mentioned in #17. I just started the course and created a new repo today.

<img width="890" alt="Screen Shot 2021-06-29 at 12 22 04 PM" src="https://user-images.githubusercontent.com/3250463/123855323-a3573580-d8d4-11eb-8bfc-e161c48121fb.png">

**Comment by MikeMcC399** [comment]
@a-a-ron / @hectorsector 
Are there any plans to fix this? The issue is ~~6~~ months old and unassigned.

**Comment by MikeMcC399** [comment]
I just happened to notice that this issue is now exactly one year old.

**Comment by MikeMcC399** [comment]
https://github.blog/2022-06-06-introducing-github-skills/ says "Learning Lab will be deprecated on September 1, 2022" and https://lab.github.com/ contains the notice "On September 1, 2022, GitHub Learning Lab will shut down."

Considering the above and the fact that this issue has been open for a year and a half I am now closing.
